spring:
  datasource:
    url: jdbc:p6spy:h2:tcp://localhost:1521/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        sysout
#        show_sql: true
        format_sql: true

logging:
  level:
#    logger
    org.hibernate.SQL: debug
    reactor: trace
#    org.hibernate.type: trace
